### ISSUE TITLE
Get down ;_;

### ISSUE THREAD

**Issue by WoruWoru** [DevinOfficial/lavalink-server#2]
Is this a problem about the host?
![image](https://user-images.githubusercontent.com/71159373/145265061-2f55f93a-7795-47c9-bee2-37906ebb1a30.png)

**Comment by WoruWoru** [comment]
I have your LL Host about a week, and this appears every day about one hour and then restart w

**Comment by DevinOfficial** [comment]
Which one host do you use? `lavalink.devin-dev.xyz` or `lava.devin-dev.xyz` ?

**Comment by WoruWoru** [comment]
hello, i tried testing both and was the same result, i was listening music and my bot suddenly stop the music for the problem with the lavalink host 😔
...with the new one host/pasas got this.
![image](https://user-images.githubusercontent.com/71159373/145272092-a922e916-f516-4f69-995c-327b7b373a2e.png)

i'm hosting my bot in replit, maybe is because that?

**Comment by WoruWoru** [comment]
i notice is SSL, srry, i tried again but now with NoSSL and was working

**Comment by DevinOfficial** [comment]
Solved, I forgot to change CNAME of `lavalink.devin-dev.xyz` to root server. Now you can use without ssl or with ssl it's your choice, and it's the same. But I recommend those without SSL it's more stable & fresh. Thanks for the report
